module.exports = {
  diff: true,
  extension: ['js'],
  package: './package.json',
  reporter: 'spec',
  slow: 75,
  timeout: 2000,
  ui: 'tdd',
  require: ['mocha/register.js'],
  'watch-files': ['src'],
  reporter: 'min',
  spec: ['src/**/*.test.js*'],
  recursive: true,
  watch: true,
};
